#  AnubisLobbyTag Config

# Database Conection
db:
  host: ""
  #port: "3306"
  dbname: ""
  user: ""
  password: ""

lobby: true # Multiple lobbys allowed
server_name: "lobby" # Name of the server in the DB, don't change once it has already been setup

# List of all the servers, place the server's server_name here
server_list:
  - teste
  - teste2

# Order Maters! Player will get the highest rank!!
# If the players has the 1st and 2nd rank, he will get the 1st
ranks:
  ##GLobal Tags - High
  - Diretor
  - Sub-Diretor
  - Gerente
  - Coordenador
  - Administrador
  - Moderador
  - Ajudante
  - Youtuber
  - MiniYT
  - Vip
  ##Vips
  #Vips Rankup-CP
  - Pro
  - Semipro
  - Amador
  #Vips Space
  - Astronauta
  - Marciano
  - Alien
  - Lun치tico
  - Terr치queo
  #Vips Ice
  - Infernal
  - Titan
  - Lord
  - Gladiador
  - Guerreiro
  #Vips Fire OP
  - Imortal
  - King
  - Prince
  - Spartan
  - Soldier
  ##Global Tags - Low
  - Membro

# Self-Explanatory
default_rank: Membro

# Group tags
# Tags teem de ter no max 16 caracters!
tags:
  ##Tags Globais
  Diretor: "&3[Diretor] "
  Sub-Diretor: "&b[Sub-Diretor] "
  Gerente: "&4[Gerente] "
  Coordenador: "&9[Coordenador] "
  Administrador: "&c[Admin] "
  Moderador: "&2[Moderador] "
  Ajudante: "&e[Ajudante] "
  Youtuber: "&c[Youtuber] &f"
  MiniYT: "&c[MiniYT] &f"
  Vip: "&e[VIP] &f"
  Membro: ""
  ##Vips
  #Vips Rankup-CP
  Pro: "&e[VIP] &f"
  Semipro: "&e[VIP] &f"
  Amador: "&e[VIP] &f"
  #Vips Space
  Astronauta: "&e[VIP] &f"
  Marciano: "&e[VIP] &f"
  Alien: "&e[VIP] &f"
  Lun치tico: "&e[VIP] &f"
  Terr치queo: "&e[VIP] &f"
  #Vips Ice
  Infernal: "&e[VIP] &f"
  Titan: "&e[VIP] &f"
  Lord: "&e[VIP] &f"
  Gladiador: "&e[VIP] &f"
  Guerreiro: "&e[VIP] &f"
  #Vips Fire OP
  Imortal: "&e[VIP] &f"
  King: "&e[VIP] &f"
  Prince: "&e[VIP] &f"
  Spartan: "&e[VIP] &f"
  Soldier: "&e[VIP] &f"

# Forced tags
forced_tags:
  # Players tto force the tag
  players:
    - zehdahorta

  # server_name of the server whose tag should be used
  server_name:
    zehdahorta: "teste2"