name: AnubisLobbyTag
main: io.github.ffy00.AnubisLobbyTag
version: 1.0
author: FFY00
softdepends: [PermissionsEX]
commands:
  forcartag:
    description: Forces player to use the tag of the provided server
    permission: anubis.tags
  desforcartag:
    description: Unsets /forcartag
    permission: anubis.tags